### ISSUE TITLE
Explanations needed

### ISSUE THREAD

**Issue by BenSeventy9** [DIY-Solar/SmartShunt#1]
I like this project more than others because of your "VEDirect Client" class. I am glad you made it public!

I have some open questions:
1. Status led: Wiring? What does it indicates? What blinking pattern? Looks like a cicle from off to on while blinking exponentially faster

2. Battery voltage: Looks like you using a voltage devider 2:1? `BatVolt += (ina226.getBusVoltage_V() * 2.0) * 100;`

3. Battery current: I testet it with a 150/75mv shunt with correct current range `ina226.setResistorRange(0.0005,150.0);`but still getting ~50% off real current. Any suggestions?

4. I would like to use "VEDirect Client" class and create my own SmartShunt project for my camper van (No WiFi only softAP for configuration). Of course I would give you as a reference. Is that OK with you?

Thanks for your answer
Ben

**Comment by Digital-MoBa** [comment]
Yes you are right, I did the project public and want to add all the stuff like schematic and components. Sadly I didn’t find the time.
1) The status LED is just basic blinking when data is requested via VEDirect. The LED is that one that is build in the ESP Wemos D1 mini.
2) Yes, the INA226 support only up to 36V. My system is on 48V, so I divide the power to the halve so the INA226 can measure up to 72V.
3) I think you forgot the “7” maybe in your post.
ina226.setResistorRange(0.**00075**,150.0);
But I think that something need to change more because you are using a 150A shunt. Because all the math is made for 100A. 
4) Yes this is okay.
